# Generated by Django 4.2.1 on 2023-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
