# Generated by Django 4.2.1 on 2023-06-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_about_delete_receipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe_about',
            old_name='password',
            new_name='receipe_discription',
        ),
    ]
